<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.0.1</Version>
    <Description>Minimalistic async wrapper around IronBeam API.</Description>
    <Authors>artemiusgreat</Authors>
    <Copyright>indemos.com</Copyright>
    <PackageProjectUrl>http://indemos.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/artemiusgreat/IronBeamBroker</RepositoryUrl>
    <PackageTags>IronBeamBroker</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="System.Interactive" Version="7.0.1" />
  </ItemGroup>

</Project>
